# Generated by Django 5.0.7 on 2024-11-13 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='场地名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='场地描述')),
                ('timerange', models.IntegerField(default=14, help_text='场地可预约的时间范围，默认为14天(两周)，如需更改可以自行增加或者减少')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该场地')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='上传一张新闻图片', upload_to='news_images/')),
                ('title', models.CharField(help_text='新闻标题', max_length=255)),
                ('description', models.TextField(help_text='新闻描述')),
                ('url', models.URLField(help_text='新闻详情的链接')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('wechat_id', models.CharField(help_text='微信唯一标识符', max_length=255, unique=True)),
                ('wechat_nickname', models.CharField(blank=True, help_text='微信昵称', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='电子邮箱', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='姓', max_length=30)),
                ('first_name', models.CharField(blank=True, help_text='名', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='性别', max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='出生年月', null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='钱包余额', max_digits=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='combo', help_text='场地组合名称', max_length=100)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='折扣值（可选）', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='组合描述')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='固定价格（可选）', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该组合')),
                ('combined_courts', models.ManyToManyField(help_text='两个或更多组合的场地', to='api.court')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='充值金额', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='充值时间')),
                ('notes', models.CharField(blank=True, help_text='备注', max_length=255)),
                ('admin_user', models.ForeignKey(help_text='操作管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recharges', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='充值用户', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='开始时间')),
                ('end_time', models.TimeField(help_text='结束时间')),
                ('day_of_week', models.IntegerField(default=0, help_text='周几：1=周一，2=周二, ... ,7=周日, 0=每天')),
                ('price', models.DecimalField(decimal_places=2, help_text='价格', max_digits=6)),
                ('is_peak', models.BooleanField(default=False, help_text='是否为高峰时段')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('court', models.ForeignKey(help_text='关联的场地', on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='api.court')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='预约日期', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='预定价格', max_digits=6)),
                ('is_combo', models.BooleanField(default=False, help_text='是否为组合价格')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='预约状态', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='预约创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='预约最后更新时间')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='订单唯一标识符', unique=True)),
                ('user', models.ForeignKey(help_text='预约的用户', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(help_text='预约的时间段', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.timeslot')),
            ],
        ),
    ]
