# Generated by Django 5.0.7 on 2024-08-04 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='场地名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='场地描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('wechat_id', models.CharField(help_text='微信唯一标识符', max_length=255, unique=True)),
                ('wechat_nickname', models.CharField(blank=True, help_text='微信昵称', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='电子邮箱', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='姓', max_length=30)),
                ('first_name', models.CharField(blank=True, help_text='名', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='性别', max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='出生年月', null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='钱包余额', max_digits=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='开始时间')),
                ('end_time', models.TimeField(help_text='结束时间')),
                ('day_of_week', models.IntegerField(default=0, help_text='周几：1=周一，2=周二, ... ,7=周日, 0=每天')),
                ('price', models.DecimalField(decimal_places=2, help_text='价格', max_digits=6)),
                ('is_peak', models.BooleanField(default=False, help_text='是否为高峰时段')),
                ('court', models.ForeignKey(help_text='关联的场地', on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='api.court')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='预约日期', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='预约状态', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='预约创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='预约最后更新时间')),
                ('user', models.ForeignKey(help_text='预约的用户', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(help_text='预约的时间段', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.timeslot')),
            ],
        ),
    ]
