# Generated by Django 5.0.7 on 2024-08-04 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='订单唯一标识符', unique=True),
        ),
    ]
