# Generated by Django 5.0.7 on 2024-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_court_timerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='timerange',
            field=models.IntegerField(default=14, help_text='场地可预约的时间范围，默认为14天(两周)，如需更改可以自行增加或者减少'),
        ),
    ]
