# Generated by Django 5.0.7 on 2024-08-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_court_timerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='上传一张新闻图片', upload_to='news_images/')),
                ('title', models.CharField(help_text='新闻标题', max_length=255)),
                ('description', models.TextField(help_text='新闻描述')),
                ('url', models.URLField(help_text='新闻详情的链接')),
            ],
        ),
        migrations.AlterField(
            model_name='court',
            name='timerange',
            field=models.IntegerField(default=14, help_text='场地可预约的时间范围，默认为14天(两周)，如需更改可以自行增加或者减少'),
        ),
    ]
