# Generated by Django 5.0.7 on 2024-08-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_court_timerange'),
        ('api', '0004_image_news_alter_court_timerange'),
    ]

    operations = [
    ]
