# Generated by Django 5.0.7 on 2024-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20240827_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活该场地'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活'),
        ),
        migrations.CreateModel(
            name='CourtCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='折扣值（可选）', max_digits=5, null=True)),
                ('description', models.TextField(help_text='组合描述')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='固定价格（可选）', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('combined_courts', models.ManyToManyField(help_text='两个或更多组合的场地', to='api.court')),
            ],
        ),
    ]
