# Generated by Django 5.0.7 on 2024-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_court_is_active_timeslot_is_active_courtcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcombo',
            name='name',
            field=models.CharField(default='combo', help_text='场地组合名称', max_length=100),
        ),
    ]
