# Generated by Django 5.0.7 on 2024-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_courtcombo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcombo',
            name='description',
            field=models.TextField(blank=True, help_text='组合描述'),
        ),
    ]
