# Generated by Django 5.0.7 on 2024-10-04 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_courtcombo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='预定价格', max_digits=6),
        ),
        migrations.AlterField(
            model_name='courtcombo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活该组合'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('cabf645a-b8fe-4e04-88f1-02e87ead34c4'), editable=False, help_text='订单唯一标识符', unique=True),
        ),
    ]
