# Generated by Django 5.0.7 on 2024-10-21 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reservation_price_alter_courtcombo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='是否为组合价格'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='订单唯一标识符', unique=True),
        ),
    ]
